output_dir: products
force_rebuild: false
upload_to_s3: true
upload_to_s3_prefix: s3://dea-public-data-dev/projects/burn_cube/derivative/dea_burn_severity/result
app_name: Burn_Severity
output_crs: EPSG:3577
resolution:
  - -10
  - 10
s2_products:
  - ga_s2am_ard_3
  - ga_s2bm_ard_3
  - ga_s2cm_ard_3
s2_measurements:
  - nbart_blue
  - nbart_green
  - nbart_red
  - nbart_nir_1
  - nbart_nir_2
  - nbart_swir_2
  - nbart_swir_3
  - oa_nbart_contiguity
  - oa_s2cloudless_mask
pre_fire_buffer_days: 50
nli_holding_days: 7
post_fire_start_days: 15
post_fire_window_days: 60
grass_classes:
  - 3
  - 14
  - 15
  - 16
  - 17
  - 18
  - 21
  - 32
  - 33
  - 34
  - 35
  - 36
  - 39
  - 50
  - 51
  - 52
  - 53
  - 54
  - 57
  - 78
  - 79
  - 80
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  - 89
  - 90
  - 91
  - 92
  - 94
  - 95
  - 96
  - 97
db_table: nli_lastboundaries_trigger
severity_list_dict:
  0: Unburnt
  1: Grass_extent
  2: Low
  3: Medium
  4: High
  5: Extreme
db_columns:
  - fire_id
  - fire_name
  - fire_type
  - ignition_date
  - capt_date
  - capt_method
  - area_ha
  - perim_km
  - state
  - agency
  - date_retrieved
  - date_processed
db_geom_column: geom
db_output_crs: EPSG:3577
