name: DEA Burn Severity App Image Push

env:
  IMAGE_NAME: geoscienceaustralia/dea-burn-severity

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '!configs/*'
      - 'Dockerfile'
      - 'constraints.txt'
      - 'requirements.txt'
      - '.github/workflows/dea-burn-severity-image.yaml'

  release:
    types: [created, edited]


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  push_ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::538673716275:role/burn_seveirty_github-actions-role
          aws-region: ap-southeast-2

      - name: Get tag for this build if it exists
        if: github.event_name == 'release'
        run: |
          echo "RELEASE=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV

      - name: Push release image to ECR
        uses: whoan/docker-build-with-cache-action@master
        if: github.event_name == 'release'
        with:
          registry: 538673716275.dkr.ecr.ap-southeast-2.amazonaws.com
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: ${{ env.RELEASE }}

      - name: Get git commit hash for push to main
        if: github.event_name != 'release'
        run: |
          echo "TAG=dev$(git rev-parse --short HEAD)" \
          >> $GITHUB_ENV

      - name: Push unstable image to ECR
        uses: whoan/docker-build-with-cache-action@master
        if: github.event_name != 'release'
        with:
          registry: 538673716275.dkr.ecr.ap-southeast-2.amazonaws.com
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest,${{ env.TAG }}